spring.application.name=backend

# H2 In-Memory Database Configuration
spring.datasource.url=jdbc:h2:mem:aiprojectarchitect_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080

# Gemini API Integration
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent
gemini.api.key=""
